#ifndef WS_STATUS_H
#define WS_STATUS_H

typedef enum
{
    WS_STATUS_NOT_INITIALIZED = 0,
    WS_STATUS_READY = 1,
    WS_STATUS_DISABLED = 2,
    WS_STATUS_TIMEOUT = 3,
    WS_STATUS_BUS_ERROR = 4,
    WS_STATUS_INVALID_SAMPLE = 5,
    WS_STATUS_BUSY = 6,
    WS_STATUS_OVERFLOW = 7,
    WS_STATUS_UNDERRUN = 8,
    WS_STATUS_UNSUPPORTED = 9,
    WS_STATUS_INTERNAL_ERROR = 10
} ws_status_t;

#endif
