;*************************************************************
; WheelSense Station
;*************************************************************

[platformio]
globallib_dir = ../LilyGo-Camera-Series-master/lib

[env:t-camera-sim]
platform = espressif32@6.3.0
board = esp32s3box
framework = arduino
upload_speed = 921600
monitor_speed = 115200

build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_TTGO_T_CAM_SIM

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8
    links2004/WebSockets@^2.4.1

board_build.partitions = default_16MB.csv
