#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

#define FIRMWARE_VERSION "4.0.0-ble-gateway"

#define DEFAULT_DEVICE_NAME "WS_BLEGW_01"
#define DEFAULT_ROOM_ID ""
#define DEFAULT_ROOM_NAME ""
#define DEFAULT_WHEEL_RADIUS_M 0.30f

#define SCREEN_WIDTH 135
#define SCREEN_HEIGHT 240
#define SCREEN_ROTATION 1

#define COLOR_PRIMARY 0x00FF00
#define COLOR_WARNING 0xFFA500
#define COLOR_ERROR   0xFF0000
#define COLOR_TEXT    0xFFFFFF
#define COLOR_BG      0x000000
#define COLOR_BG_LIGHT 0xAAAAAA
#define COLOR_HEADER  0x444444
#define COLOR_CYAN    0x00FFFF
#define COLOR_BLUE    0x0000FF

#define BLE_TELEMETRY_INTERVAL 1000
#define SENSOR_READ_INTERVAL 50
#define BLE_UPDATE_INTERVAL 250
#define DISPLAY_UPDATE_INTERVAL 500
#define MAIN_LOOP_IDLE_DELAY_MS 5
#define BOOT_DURATION_MS 2000

#define BATTERY_SAMPLE_INTERVAL_MS 2000
#define BATTERY_CHARGE_DEBOUNCE_SAMPLES 3
#define BATTERY_CHARGE_MIN_SWITCH_MS 6000

#define LCD_DIM_TIMEOUT_MS      15000
#define LCD_OFF_TIMEOUT_MS      60000
#define LCD_BRIGHTNESS_FULL     80
#define LCD_BRIGHTNESS_DIM      20
#define LCD_BRIGHTNESS_OFF      0

#define BLE_TELEMETRY_INTERVAL_IDLE  5000
#define SENSOR_READ_INTERVAL_IDLE   200
#define MAIN_LOOP_IDLE_DELAY_SLEEP_MS 20

#define DISPLAY_MODE_ALWAYS_ON  0
#define DISPLAY_MODE_AUTO_SLEEP 1

#endif
