"""Add Phase 1 Domain Models

Revision ID: 03d8ac91dba1
Revises: 5f91820b6334
Create Date: 2026-04-01 19:00:02.738154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d8ac91dba1'
down_revision: Union[str, None] = '5f91820b6334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('photo_url', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregivers_workspace_id'), 'caregivers', ['workspace_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_workspace_id'), 'facilities', ['workspace_id'], unique=False)
    op.create_table('caregiver_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('shift_type', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_shifts_caregiver_id'), 'caregiver_shifts', ['caregiver_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('map_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_facility_id'), 'floors', ['facility_id'], unique=False)
    op.create_index(op.f('ix_floors_workspace_id'), 'floors', ['workspace_id'], unique=False)
    op.create_table('caregiver_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_zones_caregiver_id'), 'caregiver_zones', ['caregiver_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('blood_type', sa.String(length=4), nullable=True),
    sa.Column('photo_url', sa.String(length=256), nullable=True),
    sa.Column('medical_conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('allergies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('medications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('care_level', sa.String(length=16), nullable=True),
    sa.Column('mobility_type', sa.String(length=16), nullable=True),
    sa.Column('current_mode', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_workspace_id'), 'patients', ['workspace_id'], unique=False)
    op.create_table('activity_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('caregiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_timeline_patient_id'), 'activity_timeline', ['patient_id'], unique=False)
    op.create_index(op.f('ix_activity_timeline_timestamp'), 'activity_timeline', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_timeline_workspace_id'), 'activity_timeline', ['workspace_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_workspace_id'), 'alerts', ['workspace_id'], unique=False)
    op.create_table('health_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('blood_pressure_sys', sa.SmallInteger(), nullable=True),
    sa.Column('blood_pressure_dia', sa.SmallInteger(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('pain_level', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('meal_type', sa.String(length=16), nullable=True),
    sa.Column('meal_portion', sa.String(length=16), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_observations_caregiver_id'), 'health_observations', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_health_observations_patient_id'), 'health_observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_health_observations_timestamp'), 'health_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_observations_workspace_id'), 'health_observations', ['workspace_id'], unique=False)
    op.create_table('patient_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_contacts_patient_id'), 'patient_contacts', ['patient_id'], unique=False)
    op.create_table('patient_device_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('device_role', sa.String(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_device_assignments_device_id'), 'patient_device_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_patient_device_assignments_patient_id'), 'patient_device_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_device_assignments_workspace_id'), 'patient_device_assignments', ['workspace_id'], unique=False)
    op.create_table('vital_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('rr_interval_ms', sa.Float(), nullable=True),
    sa.Column('spo2', sa.SmallInteger(), nullable=True),
    sa.Column('skin_temperature', sa.Float(), nullable=True),
    sa.Column('sensor_battery', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_readings_device_id'), 'vital_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_vital_readings_patient_id'), 'vital_readings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vital_readings_timestamp'), 'vital_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vital_readings_workspace_id'), 'vital_readings', ['workspace_id'], unique=False)
    op.add_column('rooms', sa.Column('floor_id', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('node_device_id', sa.String(length=32), nullable=True))
    op.add_column('rooms', sa.Column('room_type', sa.String(length=32), nullable=True))
    op.add_column('rooms', sa.Column('adjacent_rooms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('rooms', sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_unique_constraint(None, 'rooms', ['node_device_id'])
    op.create_foreign_key(None, 'rooms', 'floors', ['floor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'config')
    op.drop_column('rooms', 'adjacent_rooms')
    op.drop_column('rooms', 'room_type')
    op.drop_column('rooms', 'node_device_id')
    op.drop_column('rooms', 'floor_id')
    op.drop_index(op.f('ix_vital_readings_workspace_id'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_timestamp'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_patient_id'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_device_id'), table_name='vital_readings')
    op.drop_table('vital_readings')
    op.drop_index(op.f('ix_patient_device_assignments_workspace_id'), table_name='patient_device_assignments')
    op.drop_index(op.f('ix_patient_device_assignments_patient_id'), table_name='patient_device_assignments')
    op.drop_index(op.f('ix_patient_device_assignments_device_id'), table_name='patient_device_assignments')
    op.drop_table('patient_device_assignments')
    op.drop_index(op.f('ix_patient_contacts_patient_id'), table_name='patient_contacts')
    op.drop_table('patient_contacts')
    op.drop_index(op.f('ix_health_observations_workspace_id'), table_name='health_observations')
    op.drop_index(op.f('ix_health_observations_timestamp'), table_name='health_observations')
    op.drop_index(op.f('ix_health_observations_patient_id'), table_name='health_observations')
    op.drop_index(op.f('ix_health_observations_caregiver_id'), table_name='health_observations')
    op.drop_table('health_observations')
    op.drop_index(op.f('ix_alerts_workspace_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_activity_timeline_workspace_id'), table_name='activity_timeline')
    op.drop_index(op.f('ix_activity_timeline_timestamp'), table_name='activity_timeline')
    op.drop_index(op.f('ix_activity_timeline_patient_id'), table_name='activity_timeline')
    op.drop_table('activity_timeline')
    op.drop_index(op.f('ix_patients_workspace_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_caregiver_zones_caregiver_id'), table_name='caregiver_zones')
    op.drop_table('caregiver_zones')
    op.drop_index(op.f('ix_floors_workspace_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_facility_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_caregiver_shifts_caregiver_id'), table_name='caregiver_shifts')
    op.drop_table('caregiver_shifts')
    op.drop_index(op.f('ix_facilities_workspace_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_caregivers_workspace_id'), table_name='caregivers')
    op.drop_table('caregivers')
    # ### end Alembic commands ###
