"""Add workspaces and dual mode architecture

Revision ID: 5f91820b6334
Revises: 7eb2ee25df34
Create Date: 2026-04-01 00:45:29.337298

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '5f91820b6334'
down_revision: Union[str, None] = '7eb2ee25df34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
