"""Initial workspace schema

Revision ID: 7eb2ee25df34
Revises: 
Create Date: 2026-04-01 00:41:24.122027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb2ee25df34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('firmware', sa.String(length=16), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_devices_workspace_id'), 'devices', ['workspace_id'], unique=False)
    op.create_table('imu_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('ax', sa.Float(), nullable=True),
    sa.Column('ay', sa.Float(), nullable=True),
    sa.Column('az', sa.Float(), nullable=True),
    sa.Column('gx', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('gz', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('velocity_ms', sa.Float(), nullable=True),
    sa.Column('accel_ms2', sa.Float(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=True),
    sa.Column('battery_pct', sa.SmallInteger(), nullable=True),
    sa.Column('battery_v', sa.Float(), nullable=True),
    sa.Column('charging', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imu_telemetry_device_id'), 'imu_telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_imu_telemetry_timestamp'), 'imu_telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_imu_telemetry_workspace_id'), 'imu_telemetry', ['workspace_id'], unique=False)
    op.create_table('motion_training_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_label', sa.String(length=32), nullable=False),
    sa.Column('ax', sa.Float(), nullable=True),
    sa.Column('ay', sa.Float(), nullable=True),
    sa.Column('az', sa.Float(), nullable=True),
    sa.Column('gx', sa.Float(), nullable=True),
    sa.Column('gy', sa.Float(), nullable=True),
    sa.Column('gz', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('velocity_ms', sa.Float(), nullable=True),
    sa.Column('accel_ms2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motion_training_data_action_label'), 'motion_training_data', ['action_label'], unique=False)
    op.create_index(op.f('ix_motion_training_data_device_id'), 'motion_training_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_motion_training_data_session_id'), 'motion_training_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_motion_training_data_timestamp'), 'motion_training_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_motion_training_data_workspace_id'), 'motion_training_data', ['workspace_id'], unique=False)
    op.create_table('room_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_room_id', sa.Integer(), nullable=True),
    sa.Column('predicted_room_name', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(length=16), nullable=True),
    sa.Column('rssi_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_predictions_device_id'), 'room_predictions', ['device_id'], unique=False)
    op.create_index(op.f('ix_room_predictions_timestamp'), 'room_predictions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_room_predictions_workspace_id'), 'room_predictions', ['workspace_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_workspace_id'), 'rooms', ['workspace_id'], unique=False)
    op.create_table('rssi_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('rssi', sa.SmallInteger(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rssi_readings_device_id'), 'rssi_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_rssi_readings_timestamp'), 'rssi_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_rssi_readings_workspace_id'), 'rssi_readings', ['workspace_id'], unique=False)
    op.create_table('rssi_training_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=64), nullable=True),
    sa.Column('rssi_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rssi_training_data_workspace_id'), 'rssi_training_data', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rssi_training_data_workspace_id'), table_name='rssi_training_data')
    op.drop_table('rssi_training_data')
    op.drop_index(op.f('ix_rssi_readings_workspace_id'), table_name='rssi_readings')
    op.drop_index(op.f('ix_rssi_readings_timestamp'), table_name='rssi_readings')
    op.drop_index(op.f('ix_rssi_readings_device_id'), table_name='rssi_readings')
    op.drop_table('rssi_readings')
    op.drop_index(op.f('ix_rooms_workspace_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_room_predictions_workspace_id'), table_name='room_predictions')
    op.drop_index(op.f('ix_room_predictions_timestamp'), table_name='room_predictions')
    op.drop_index(op.f('ix_room_predictions_device_id'), table_name='room_predictions')
    op.drop_table('room_predictions')
    op.drop_index(op.f('ix_motion_training_data_workspace_id'), table_name='motion_training_data')
    op.drop_index(op.f('ix_motion_training_data_timestamp'), table_name='motion_training_data')
    op.drop_index(op.f('ix_motion_training_data_session_id'), table_name='motion_training_data')
    op.drop_index(op.f('ix_motion_training_data_device_id'), table_name='motion_training_data')
    op.drop_index(op.f('ix_motion_training_data_action_label'), table_name='motion_training_data')
    op.drop_table('motion_training_data')
    op.drop_index(op.f('ix_imu_telemetry_workspace_id'), table_name='imu_telemetry')
    op.drop_index(op.f('ix_imu_telemetry_timestamp'), table_name='imu_telemetry')
    op.drop_index(op.f('ix_imu_telemetry_device_id'), table_name='imu_telemetry')
    op.drop_table('imu_telemetry')
    op.drop_index(op.f('ix_devices_workspace_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
