"""Add SmartDevice model

Revision ID: bf03ac0a4d37
Revises: 8957f9d4c3ba
Create Date: 2026-04-02 01:03:44.625633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf03ac0a4d37'
down_revision: Union[str, None] = '8957f9d4c3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ha_entity_id', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_devices_ha_entity_id'), 'smart_devices', ['ha_entity_id'], unique=True)
    op.create_index(op.f('ix_smart_devices_room_id'), 'smart_devices', ['room_id'], unique=False)
    op.create_index(op.f('ix_smart_devices_workspace_id'), 'smart_devices', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_devices_workspace_id'), table_name='smart_devices')
    op.drop_index(op.f('ix_smart_devices_room_id'), table_name='smart_devices')
    op.drop_index(op.f('ix_smart_devices_ha_entity_id'), table_name='smart_devices')
    op.drop_table('smart_devices')
    # ### end Alembic commands ###
