"""add photo_records table

Revision ID: f283dfeb80d0
Revises: bf03ac0a4d37
Create Date: 2026-04-02 23:20:20.673376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f283dfeb80d0'
down_revision: Union[str, None] = 'bf03ac0a4d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=64), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_records_device_id'), 'photo_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_photo_records_photo_id'), 'photo_records', ['photo_id'], unique=True)
    op.create_index(op.f('ix_photo_records_timestamp'), 'photo_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_photo_records_workspace_id'), 'photo_records', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_records_workspace_id'), table_name='photo_records')
    op.drop_index(op.f('ix_photo_records_timestamp'), table_name='photo_records')
    op.drop_index(op.f('ix_photo_records_photo_id'), table_name='photo_records')
    op.drop_index(op.f('ix_photo_records_device_id'), table_name='photo_records')
    op.drop_table('photo_records')
    # ### end Alembic commands ###
