;*************************************************************
; BLE Indoor Localization — Tag (ESP-IDF)
; Board: M5StickC Plus2 (ESP32-PICO-V3)
;*************************************************************

[platformio]
default_envs = tag

[env:tag]
platform = espressif32@6.3.0
board = m5stick-c
framework = espidf
monitor_speed = 115200

build_flags =
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
    -DTAG_NAME=\"WS_TAG\"
    -DADV_INTERVAL_MS=200
    -DTX_POWER=ESP_PWR_LVL_P9
