; PlatformIO Project Configuration File for CUCUMBERRS Appliance Controller
; nodemcuBase ver1.0
;
; ควบคุมอุปกรณ์ไฟฟ้าทั้งบ้าน (ไฟ, แอร์, พัดลม, ทีวี)
 
[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
 
lib_deps =
    links2004/WebSockets @ ^2.4.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.10
 
build_flags =
    -D WIFI_SSID=\"WittyNotebook\"
    -D WIFI_PASSWORD=\"eornnrbs\"
 