[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
build_flags =
  -D NIMBLE_CPP_LOG_LEVEL=0
  -D CONFIG_BT_NIMBLE_DEBUG=0

lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7
  https://github.com/kokke/tiny-AES-c
  painlessmesh/painlessMesh @ ^1.4.9
  arkhipenko/TaskScheduler @ ^3.7.0