# CMake generated Testfile for 
# Source directory: C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests
# Build directory: C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ws_protocol "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_protocol.exe")
set_tests_properties(ws_protocol PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;19;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_ipc_messages "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_ipc_messages.exe")
set_tests_properties(ws_ipc_messages PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;30;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_ipc_queue "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_ipc_queue.exe")
set_tests_properties(ws_ipc_queue PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;41;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_ipc_transport "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_ipc_transport.exe")
set_tests_properties(ws_ipc_transport PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;53;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_environment_contract "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_environment_contract.exe")
set_tests_properties(ws_environment_contract PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;92;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_orientation_contract "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_orientation_contract.exe")
set_tests_properties(ws_orientation_contract PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;101;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_environment_conversion "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_environment_conversion.exe")
set_tests_properties(ws_environment_conversion PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;111;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_orientation_state "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_orientation_state.exe")
set_tests_properties(ws_orientation_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;121;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_sensor_schedule "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_sensor_schedule.exe")
set_tests_properties(ws_sensor_schedule PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;131;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_ui_state "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_ui_state.exe")
set_tests_properties(ws_ui_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;144;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_lvgl_state_contract "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_lvgl_state_contract.exe")
set_tests_properties(ws_lvgl_state_contract PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;157;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
add_test(ws_ui_diagnostic_consumption "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/build-sanitize/tests/test_ui_diagnostic_consumption.exe")
set_tests_properties(ws_ui_diagnostic_consumption PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;170;add_test;C:/Users/worap/Documents/Project/wheelsense-platform/firmware/WheelSense_E84/host_sim/tests/CMakeLists.txt;0;")
